SITES = [
    {"category": "E-commerce", "name": "Lamoda", "url": "https://www.lamoda.ru"},
    {"category": "E-commerce", "name": "Яндекс Маркет", "url": "https://market.yandex.ru"},
    {"category": "E-commerce", "name": "СберМегаМаркет", "url": "https://megamarket.ru"},
    {"category": "Банки", "name": "Альфа-Банк", "url": "https://alfabank.ru"},
    {"category": "Банки", "name": "ВТБ", "url": "https://www.vtb.ru"},
    {"category": "Банки", "name": "Совкомбанк", "url": "https://sovcombank.ru"},
    {"category": "Застройщики", "name": "ПИК", "url": "https://www.pik.ru"},
    {"category": "Застройщики", "name": "Самолёт", "url": "https://samolet.ru"},
    {"category": "Застройщики", "name": "А101", "url": "https://a101.ru"},
    {"category": "Телеком", "name": "Билайн", "url": "https://beeline.ru"},
    {"category": "Телеком", "name": "МегаФон", "url": "https://megafon.ru"},
    {"category": "Телеком", "name": "Ростелеком", "url": "https://rt.ru"},
    {"category": "B2B", "name": "КАМАЗ", "url": "https://kamaz.ru"},
    {"category": "B2B", "name": "Северсталь", "url": "https://severstal.com"},
    {"category": "B2B", "name": "Сибур", "url": "https://www.sibur.ru"},
    {"category": "Сервисы", "name": "Авито", "url": "https://www.avito.ru"},
    {"category": "Сервисы", "name": "ЦИАН", "url": "https://cian.ru"},
    {"category": "Сервисы", "name": "HeadHunter", "url": "https://hh.ru"},
]
